# Generated by Django 5.0.3 on 2024-03-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_societate', models.CharField(max_length=50)),
                ('nume_user', models.CharField(max_length=50)),
                ('descriere_ticket', models.CharField(max_length=1000)),
                ('status_ticket', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserTicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_user', models.CharField(max_length=50)),
                ('data_inregistrare_user_ticket', models.CharField(max_length=50)),
                ('data_inchidere_user_ticket', models.CharField(max_length=1000)),
            ],
        ),
    ]
