# Generated by Django 5.0.3 on 2024-03-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_user', models.CharField(max_length=50)),
                ('prenume_user', models.CharField(max_length=50)),
                ('email_user', models.EmailField(max_length=50)),
                ('telefon', models.CharField(max_length=12)),
                ('nume_societate', models.CharField(max_length=50)),
                ('cui_societate', models.CharField(max_length=10)),
                ('angajat', models.BooleanField(default=False)),
            ],
        ),
    ]
